# Generated by Django 2.0.9 on 2018-12-05 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id_cliente', models.AutoField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=50)),
                ('comunas', models.CharField(max_length=40)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ordendetrabajo',
            fields=[
                ('id_orden', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('run_cliente', models.CharField(max_length=10, null=True)),
                ('nombre_cliente', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora_ini', models.DateField()),
                ('hora_term', models.DateField()),
                ('id_ascensor', models.CharField(max_length=10)),
                ('modelo_ascensor', models.CharField(max_length=20)),
                ('descripcion_falla', models.CharField(max_length=300, null=True)),
                ('descripcion_reparacion', models.CharField(max_length=300, null=True)),
                ('piezas_cambiadas', models.CharField(max_length=200, null=True)),
                ('nombre_receptor', models.CharField(max_length=50, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPerris.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id_usuario', models.AutoField(max_length=6, primary_key=True, serialize=False)),
                ('email_usuario', models.EmailField(max_length=40)),
                ('run_usuario', models.CharField(max_length=10)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('fechanac_usuario', models.DateField()),
                ('contra', models.CharField(max_length=30)),
                ('id_tipo', models.CharField(choices=[(1, 'Mantenedor'), (2, 'Administrador')], default=1, max_length=1)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordendetrabajo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPerris.usuario'),
        ),
    ]
