# Generated by Django 2.1 on 2018-10-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adoptante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_email', models.CharField(max_length=40)),
                ('_run', models.CharField(max_length=10)),
                ('_nombreCompleto', models.CharField(max_length=50)),
                ('_fono', models.CharField(max_length=9)),
                ('_fecNac', models.DateField()),
                ('_region', models.CharField(max_length=20)),
                ('_comuna', models.CharField(max_length=20)),
                ('_tipovivienda', models.CharField(choices=[('G', 'Casa con patio grande'), ('P', 'Casa con patio grande'), ('M', 'Mercedes'), ('D', 'Departamento')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_foto', models.ImageField(upload_to='')),
                ('_nombrePerro', models.CharField(max_length=30)),
                ('_razaPredom', models.CharField(max_length=30)),
                ('_descrip', models.CharField(max_length=30)),
                ('_estado', models.CharField(choices=[('R', 'Rescatado'), ('D', 'Disponible'), ('A', 'adoptado')], default='R', max_length=1)),
            ],
        ),
    ]
