# Generated by Django 2.1 on 2018-10-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerris', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptante',
            old_name='_comuna',
            new_name='comunas',
        ),
        migrations.RenameField(
            model_name='adoptante',
            old_name='_email',
            new_name='email_usuario',
        ),
        migrations.RenameField(
            model_name='adoptante',
            old_name='_fecNac',
            new_name='fechanac_usuario',
        ),
        migrations.RenameField(
            model_name='adoptante',
            old_name='_fono',
            new_name='fono_usuario',
        ),
        migrations.RenameField(
            model_name='adoptante',
            old_name='_nombreCompleto',
            new_name='nombre_usuario',
        ),
        migrations.RenameField(
            model_name='adoptante',
            old_name='_region',
            new_name='regiones',
        ),
        migrations.RenameField(
            model_name='adoptante',
            old_name='_run',
            new_name='run_usuario',
        ),
        migrations.RemoveField(
            model_name='adoptante',
            name='_tipovivienda',
        ),
        migrations.AddField(
            model_name='adoptante',
            name='tipo_vivienda',
            field=models.CharField(choices=[('G', 'Casa con patio grande'), ('P', 'Casa con patio grande'), ('S', 'casa_sin_patio'), ('D', 'Departamento')], default='G', max_length=1),
        ),
    ]
