# Generated by Django 2.1.3 on 2018-11-07 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerris', '0002_auto_20181106_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.CharField(choices=[('R', 'Rescatado'), ('D', 'Disponible'), ('A', 'Adoptado')], default='R', max_length=1),
        ),
    ]
