# Generated by Django 2.1 on 2018-10-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerris', '0002_auto_20181026_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='_descrip',
            new_name='descrip',
        ),
        migrations.RenameField(
            model_name='perro',
            old_name='_estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='perro',
            old_name='_foto',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='perro',
            old_name='_nombrePerro',
            new_name='nombre_perro',
        ),
        migrations.RenameField(
            model_name='perro',
            old_name='_razaPredom',
            new_name='raza_predom',
        ),
        migrations.RemoveField(
            model_name='adoptante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='id',
        ),
        migrations.AddField(
            model_name='perro',
            name='id_perro',
            field=models.CharField(default='0', max_length=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='run_usuario',
            field=models.CharField(help_text='run', max_length=10, primary_key=True, serialize=False),
        ),
    ]
