# Generated by Django 2.1.2 on 2018-11-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerris', '0002_auto_20181106_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='comunas',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='regiones',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='adoptante',
            name='tipo_vivienda',
            field=models.IntegerField(choices=[('G', 'Casa con patio grande'), (1, 'Casa con patio grande'), (2, 'Casa sin patio'), (3, 'Departamento')], default=1),
        ),
    ]
