# Generated by Django 2.1 on 2018-10-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerris', '0004_auto_20181026_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='tipo_vivienda',
            field=models.CharField(choices=[('G', 'Casa con patio grande'), ('P', 'Casa con patio grande'), ('S', 'Casa sin patio'), ('D', 'Departamento')], default='G', max_length=1),
        ),
    ]
