# Generated by Django 2.1 on 2018-10-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerris', '0005_auto_20181026_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptante',
            name='run_usuario',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
