# Generated by Django 2.1 on 2018-10-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerris', '0006_auto_20181026_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
