# Generated by Django 2.1 on 2018-10-26 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerris', '0007_auto_20181026_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perro',
            old_name='descrip',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='perro',
            old_name='raza_predom',
            new_name='raza_predominante',
        ),
    ]
