# Generated by Django 2.1.2 on 2018-11-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerris', '0008_auto_20181026_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('email_usuario', models.CharField(max_length=40)),
                ('uname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('psw', models.CharField(max_length=40)),
                ('tip', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='perro',
            name='foto',
        ),
    ]
