# Generated by Django 2.1.3 on 2018-11-05 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerris', '0008_auto_20181026_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='foto',
        ),
    ]
