# Generated by Django 2.1.2 on 2018-11-05 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPerris', '0009_auto_20181105_1810'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='usuarioUwu',
        ),
    ]
